<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXa3d58i\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXa3d58i/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXa3d58i.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXa3d58i\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXa3d58i\appProdProjectContainer([
    'container.build_hash' => 'Xa3d58i',
    'container.build_id' => '783f8ba3',
    'container.build_time' => 1587887614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXa3d58i');
